spring.application.name=aptitude-practice

# Database Configuration for PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# JWT Secret Configuration
jwt.secret=${JWT_SECRET}
jwt.expirationMs=86400000

# Make the server accessible on the network
server.address=0.0.0.0
server.port=${PORT:8080}

# SMTP Configuration (For Forgot Password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true